### ISSUE TITLE
Seems to do nothing, what is wrong?

### ISSUE THREAD

**Issue by shawe** [backup-manager/backup-manager#116]
Doing this:

>          const path = "tmp/" . FS_TMP_NAME . "sql_backups";
>          ...
>          $manager = require 'plugins/backup_restore/config/bootstrap.php';
>          $file = self::path . '/backup_' . date('d-m-Y_H-i-s') . '.sql';
>          $manager->makeBackup()->run('production', [
>                  new Destination('local', $file)
>              ], 'gzip');

On my code, no backup file generate, and no errors or warnings, what I'm doing wrong or what I can try to change?

**Comment by shawe** [comment]
@ShawnMcCool thanks for no reply and close the issue, seems to be normal on this project comparing to others issues closed also without replies. I suppose that is not directly important to you, but this is no reason for don't reply.

I see that we solve the problem some months ago without using this project that look good enough for don't do the same thing again, but the lack of a reply force us to try it in another direction.

**Comment by ShawnMcCool** [comment]
The issue was from 7 months ago. Nobody responded to provide support so it seemed pointless to keep it around. 

I do not provide guaranteed support. 

Periodically I look through issues and pull requests and merge / close them when it seems appropriate. Pull requests I merge often, issues that are 7 months old I close always, and sometimes I reply if I have the time.

But, time is money and I don't have enough of either.

If you'd like to support this package by responding to issues or maintaining the package by sending pull requests then your work would be appreciated by those who benefit from it. But, I imagine that your time is similarly limited.
