### ISSUE TITLE
Manager properties should be protected (cannot easily extend the Manager)

### ISSUE THREAD

**Issue by thomasfw** [backup-manager/backup-manager#152]
I'm extending the default `Manager` class in order to register a new cleanup Procedure method. However, the class' properties are private, meaning that instead of just adding an additional method I need to redeclare everything.

What we should be able to write...

```php
use Acme\CleanupProcedure;
use BackupManager\Manager as BackupManager;

/**
 * Custom BackupManager\Manager,
 * registers a new clean up procedure.
 */
class Manager extends BackupManager
{
    /**
     * @return CleanupProcedure
     */
    public function cleanUp() {
        return new CleanupProcedure(
            $this->filesystems,
            $this->databases,
            $this->compressors,
            $this->getShellProcessor()
        );
    }
}
```

The monstrosity we need to write...

```php
use Acme\CleanupProcedure;
use BackupManager\Manager as BackupManager;

use BackupManager\Filesystems\FilesystemProvider;
use BackupManager\Databases\DatabaseProvider;
use BackupManager\Compressors\CompressorProvider;

/**
 * Custom BackupManager\Manager,
 * registers a new clean up procedure.
 */
class Manager extends BackupManager
{
    /** 
     * @var FilesystemProvider 
     */
    protected $filesystems;
    
    /** 
     * @var DatabaseProvider 
     */
    protected $databases;
   
   /** 
     * @var CompressorProvider 
     */
    protected $compressors;

    /**
     * @param FilesystemProvider $filesystems
     * @param DatabaseProvider $databases
     * @param CompressorProvider $compressors
     */
    public function __construct(FilesystemProvider $filesystems, DatabaseProvider $databases, CompressorProvider $compressors) 
    {
        $this->filesystems = $filesystems;
        $this->databases = $databases;
        $this->compressors = $compressors;

        parent::__construct( $filesystems, $databases, $compressors );
    }

    /**
     * @return CleanupProcedure
     */
    public function cleanUp() {
        return new CleanupProcedure(
            $this->filesystems,
            $this->databases,
            $this->compressors,
            $this->getShellProcessor()
        );
    }
}
```

---

```php
/** @var FilesystemProvider */
private $filesystems;
/** @var DatabaseProvider */
private $databases;
/** @var CompressorProvider */
private $compressors;
```

**Comment by ShawnMcCool** [comment]
Hello Thomas. Thanks for writing in and bringing this up. I can see that we are lacking a bit of documentation.

[This Manager class](https://github.com/backup-manager/backup-manager/blob/master/src/Manager.php) was really only ever meant to be a shortcut. It's a simple facade.

I'm personally much more comfortable with consumers implementing their own facade for their applications. It's generally recommended to have such a construct in place so that your application is consuming your own backup management interface in all places except for one.

At every location that we mark something 'protected' we're agreeing to maintain an internal implementation as an API. This package is designed to avoid taking on such extra responsibilities (so that we can focus on the necessary stability maintenance alone) while making it easy for consumers to utilize the tool as they please.

It would have been much better for us to have set up this expectation from the beginning. Then you would not have had to go through this frustrating process. I'd like to apologize for that and promise that I will update the documentation soon.
