### ISSUE TITLE
Add support for encryption

### ISSUE THREAD

**Issue by RickvdP** [backup-manager/backup-manager#25]
Hi guys,

Would it be possible to add an encryptor that encrypts the compressed package? Might be an idea to add an encryption interface to allow multiple encryption types (openssl/gpg).

I could try to send a PR if this sounds good for you guys, but realistically I won't have time the coming weeks.

Thanks!

**Comment by sagikazarmark** [comment]
@RickvdP from your description about your architecture I guess it is not some small database server serving a few Wordpress sites. While I think PHP is awesome, and most of the tools, microservices are written in PHP for me, the database layer is a very sensitive one and you might want to use some alternative tools and not PHP. (Full disclosure: I think implementing encryption is a great idea)

For bigger systems where there are more than a few megabytes of data you logical backups aren't really a good solution. (Logical backups: creating backups using SQL commands, mysqldump and backup-manager does this.) Instead you could use [Percona XtraBackup](https://www.percona.com/software/percona-xtrabackup) (or some similar software) to create physical backups (copy the underlying files). AFAIK Percona has already encryption implemented, but since it can be used from shell, you can write a simple script to compress and encrypt it with any solution you want.

This is specifically true for the use case and architecture @RickvdP mentioned.

Again, I use BackupManager and I think encryption is a great idea, but it is not always the right tool to use.
