### ISSUE TITLE
Delete older backups option

### ISSUE THREAD

**Issue by nicekiwi** [backup-manager/backup-manager#65]
Allow an option to be set to scan all files in backup dir and delete all older than X days.

**Comment by ShawnMcCool** [comment]
I think that "rolling backup" is a great idea for a new procedure.

**Comment by Houbsi** [comment]
is there someone working on this one?

**Comment by ShawnMcCool** [comment]
@Houbsi I don't have the time to work on this procedure. However, I'd be glad to help by discussing it. Let me know what you think.

**Comment by Houbsi** [comment]
Hi @ShawnMcCool i would gladly help with the procedure. But i never worked with "foreign" Code and I'm having a hart time getting into your codebase.

**Comment by ShawnMcCool** [comment]
Hi @Houbsi,

The codebase is distributed into the following components:

Tasks: https://github.com/backup-manager/backup-manager/tree/master/src/Tasks

Tasks provide a single operation. For example, `DumpDatabase` or `TransferFile`. In this folder https://github.com/backup-manager/backup-manager/tree/master/src/Tasks/Storage there is a `DeleteFile` task. 

The filesystem operations are provided from the Flysystem library. http://flysystem.thephpleague.com/

The tasks are combined into procedures. Check out some of the procedures here to see how Tasks are combined into sequences and then executed.

Procedures: https://github.com/backup-manager/backup-manager/tree/master/src/Procedures

There are a few ways to perhaps approach this problem. The EASIEST that I can think of (there may be easier) would be to just use a predictable naming strategy. Something like `Databasename_Year-Month-Day.sql.gz`.

If you do this, then you can just generate the filename for the previous day. You can create a Procedure in your application called something like.. "RemoveOldBackups" and run it after you run a backup.

The "complicated" part of the library is really the `Providers` because they need to deliver a bunch of different services based on configuration. For example, the https://github.com/backup-manager/backup-manager/blob/master/src/Filesystems/FilesystemProvider.php

But, if you look at the modular form of filesystems https://github.com/backup-manager/backup-manager/blob/master/src/Filesystems/Awss3Filesystem.php you can see that they're just small objects that know how to bootstrap Flysystem based on configuration. It's not too rough.

Maybe this helps you get started a bit. Feel free to talk to me about how you'd like it to run or any questions that you have.
